Assignment10 (#59)
* added pckr

* fmt pckr

* fmt pckr

* modify to cehck

* updated ami

* Changed ami

* Update buildpckr.yml

* Update buildpckr.yml

diff --git a/.github/workflows/buildpckr.yml b/.github/workflows/buildpckr.yml
--- a/.github/workflows/buildpckr.yml
+++ b/.github/workflows/buildpckr.yml
@@ -92,6 +92,10 @@ jobs:
               printf "\nInstance refresh successful!"
               break
            fi
+           if [ "$instance_refresh_status" = "Cancelling" ] || [ "$instance_refresh_status" = "Cancelled" ] || [ "$instance_refresh_status" = "Failed" ]; then
+             printf "\nInstance refresh failed!"
+            exit 1
+            fi
             echo -ne "."
             sleep 10
           done
